"use strict";
const VERIFIED={baseUrl:"{{VERIFIED_BASE_URL}}",address:"{{VERIFIED_ADDRESS}}",phone:"{{VERIFIED_PHONE}}",email:"{{VERIFIED_EMAIL}}",legalAge:"{{VERIFIED_LEGAL_AGE}}",events:[],broadcasts:[],results:[]};
const isVerified=v=>typeof v==="string"&&!/^\{\{VERIFIED_/.test(v)&&v.trim()!=="";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
document.addEventListener("DOMContentLoaded",()=>{
  const menu=$("#mobile-menu"),toggle=$(".menu-toggle"),close=$(".menu-close");
  const setMenu=open=>{if(!menu||!toggle)return;menu.hidden=!open;toggle.setAttribute("aria-expanded",String(open));document.body.style.overflow=open?"hidden":"";if(open)close?.focus();};
  toggle?.addEventListener("click",()=>setMenu(true));close?.addEventListener("click",()=>setMenu(false));$$('#mobile-menu a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
  const safeGet=k=>{try{return localStorage.getItem(k)}catch(e){return null}},safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}};
  const banner=$("[data-cookie-banner]"),cm=$("[data-cookie-modal]");
  const hideBanner=()=>{if(!banner)return;banner.classList.add("is-hidden");banner.hidden=true;banner.setAttribute("aria-hidden","true")};
  const showBanner=()=>{if(!banner)return;banner.classList.remove("is-hidden");banner.hidden=false;banner.setAttribute("aria-hidden","false")};
  if(safeGet("spin-casino-nz-privacy-v1"))hideBanner();else showBanner();
  $("[data-cookie-accept]")?.addEventListener("click",()=>{hideBanner();safeSet("spin-casino-nz-privacy-v1","accepted")});
  $("[data-cookie-deny]")?.addEventListener("click",()=>{hideBanner();safeSet("spin-casino-nz-privacy-v1","rejected")});
  const openPrefs=()=>{hideBanner();if(cm){cm.hidden=false;document.body.style.overflow="hidden";$("[data-cookie-close]",cm)?.focus()}};
  $("[data-cookie-manage]")?.addEventListener("click",openPrefs);$$('[data-open-cookie]').forEach(b=>b.addEventListener('click',openPrefs));
  const closePrefs=()=>{if(cm)cm.hidden=true;document.body.style.overflow=""};$("[data-cookie-close]")?.addEventListener("click",closePrefs);
  $("[data-cookie-save]")?.addEventListener("click",()=>{const v=$("[data-analytics-toggle]")?.checked?"analytics":"essential";safeSet("spin-casino-nz-privacy-v1",v);closePrefs()});
  $$('.accordion article>button').forEach(btn=>btn.addEventListener('click',()=>{const panel=btn.nextElementSibling,open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));panel.hidden=open;btn.querySelector('b').textContent=open?'+':'−'}));
  const gm=$("[data-gallery-modal]"),gmi=gm?.querySelector('img');$$('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{if(gm&&gmi){gmi.src=b.dataset.gallery;gm.hidden=false;document.body.style.overflow='hidden'}}));
  const closeGallery=()=>{if(gm)gm.hidden=true;document.body.style.overflow=''};$("[data-gallery-close]")?.addEventListener('click',closeGallery);
  $$('[data-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const state=$('.form-state',form);if(!form.checkValidity()){form.reportValidity();return};if(state)state.textContent=form.dataset.form==='tournament'?'Your request was received. A seat is final only after confirmation by the physical venue.':'Thank you. Your information request has been received.';form.reset()}));
  const filters=$$('[data-filter]');filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('[data-event-type]').forEach(card=>card.hidden=btn.dataset.filter!=='all'&&card.dataset.eventType!==btn.dataset.filter)}));
  $$('[data-verified-section]').forEach(s=>{const key=s.dataset.verifiedSection;if(Array.isArray(VERIFIED[key])&&VERIFIED[key].length)s.hidden=false;else s.hidden=true});
  $$('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());
  const top=$('.back-to-top');window.addEventListener('scroll',()=>top?.classList.toggle('visible',scrollY>600),{passive:true});top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){setMenu(false);closePrefs();closeGallery()}});
});
